apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: prometheus-test-demo
  name: prometheus-test-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-test-demo
  template:
    metadata:
      labels:
        app: prometheus-test-demo
    spec:
      containers:
      - image: test-harbor.daocloud.io/library/prometheus-test-demo:{VERSION}
        name: prometheus-test-demo
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-test-demo
spec:
  type: NodePort
  selector:
    app: prometheus-test-demo
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
